### ISSUE TITLE
网口协商速率降低

### ISSUE THREAD

**Issue by L1cardo** [stupidloud/nanopi-openwrt#1153]
软路由的2.5g网口连接至nas，一段时间内会稳定的显示协商速率为2.5G，但是不知过多久就会降低为100M

这是nas刚重启时：
<img width="419" alt="image" src="https://user-images.githubusercontent.com/33802186/171097274-0c59e5ba-99d7-4729-9802-6468f55eb3e8.png">

这是运行一段时间后：
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/33802186/171097299-f555e792-dada-4065-8f8f-56a9bdc1194a.png">

**Comment by vanadissss** [comment]
同问，问题解决了吗？我也是这个问题，我降速的接口是LAN口。

**Comment by supperbo** [comment]
BIOS电源管理

**Comment by vanadissss** [comment]
我的问题解决了，后面发现是温度的问题，机器大概高于65摄氏度，LAN口就会从千兆变百兆，可能是夏天天气热了吧，冬天就没有这个问题。装了一个散热小风扇解决了。
