### ISSUE TITLE
fork后，自定义添加插件 `luci-app-frpc`失败

### ISSUE THREAD

**Issue by coppea** [stupidloud/nanopi-openwrt#1262]
能否添加luci-app-frpc支持

**Comment by coppea** [comment]
不支持此版本frpc，http://mirrors.tencent.com/lede/snapshots/packages/aarch64_generic/luci/luci-app-frpc_git-22.229.49012-175487f_all.ipk，安装成功，但是在服务不显示

不过支持基本不维护的旧版本frpc ，https://github.com/kuoruan/luci-app-frpc，在服务能显示


能否查看一下是什么原因不支持frpc？

**Comment by john5du** [comment]
试试 CONFIG_PACKAGE_luci-app-frpc=y

**Comment by coppea** [comment]
能否添加luci-app-frpc支持
