### ISSUE TITLE
r2s  安装固件偷跑流量情况，请问是设置问题还是什么问题？

### ISSUE THREAD

**Issue by GusRoth** [stupidloud/nanopi-openwrt#1285]
我下载的是那个r2s固件，r2s.img.gz，作为旁路由使用。家庭网络结构是，三个mesh路由有线回程到光猫旁的交换机，交换机上再接一个旁路由r2s。

运行了两天，只开启了Passwall，开了主开关和socks开关。

然后出现了我的梯子流量偷跑的情况，一天跑了2.8G。

而我家庭用到旁路由http代理的软件在白天是没有的，只有晚上我的主机和游戏机才会用到，所以是什么原因？

**Comment by poctopus** [comment]
无非就是两个原因：
1、梯子泄露了；
2、passwall设置有问题；

**Comment by GusRoth** [comment]
破案了，因为switch会一直跑流量，一天大概3G…
如果有大佬看到我这里，可以告诉我怎么让他不休眠也一直跑流量吗？我现在只能把他断网了
