### ISSUE TITLE
终端在线升级卡进度92%

### ISSUE THREAD

**Issue by wuai1024** [stupidloud/nanopi-openwrt#1303]
我是在群晖里使用虚拟机安装的 x86 版本，在终端里直接更新升级就会卡死，然后cpu负载就在 36%左右。

日常正常使用，cpu < 1%

然后就能重装

有没有什么好的办法，能直接下载了固件，点击升级就可以上传更新的。

**Comment by wuai1024** [comment]
有人遇到吗？

**Comment by stupidloud** [comment]
x86不如直接用管理后台的升级方式吧

**Comment by wuai1024** [comment]
> x86不如直接用管理后台的升级方式吧

后台管理需要上传哪个文件，我看上面显示的需要 sysupgrade 但是我不知道这个文件在哪？

**Comment by stupidloud** [comment]
![image](https://github.com/stupidloud/nanopi-openwrt/assets/56048681/fd94de22-37e4-478c-a075-263f51dfbb3a)
这三个都可以 ，你根据需要选择

**Comment by wuai1024** [comment]
> ![image](https://user-images.githubusercontent.com/56048681/258713841-fd94de22-37e4-478c-a075-263f51dfbb3a.png) 这三个都可以 ，你根据需要选择

感谢，解决了。我之前每次更新都是重装的，太麻烦了。
