### ISSUE TITLE
R6S固件无法启动

### ISSUE THREAD

**Issue by ashton2914** [stupidloud/nanopi-openwrt#1347]
设备：R6S 8+32G
SD卡：三星EVO plus 64G
固件： 20240227版

刷入固件到SD卡，插入设备启动，电源灯常亮，系统没有被引导

**Comment by stupidloud** [comment]
换个卡试试

**Comment by ashton2914** [comment]
> 换个卡试试

看来三星的卡并不可以, 换了官方推荐的闪迪卡可以正常启动了
