### ISSUE TITLE
R2S为啥怎么弄都无法PPPOE拨号

### ISSUE THREAD

**Issue by ptzzy2569** [stupidloud/nanopi-openwrt#279]
R2S为啥怎么弄都无法PPPOE拨号？换了我的K2P就可以拨号。一换到R2S就没办法拨号。几个版本都试过了。不知道问题出在哪里。看几个UP主都可以。拨号的数据都是0

**Comment by Deckard-f-Cain** [comment]
你看一下光猫的ip，可能跟你R2S冲突了吧！建议吧r2s的ip改到与K2P一致，应该就可以了。

**Comment by xftesla** [comment]
我也发现有这样问题，我的光猫IP确定是和r2s不同，换其他硬路由器拨号就没问题

**Comment by ptzzy2569** [comment]
好像是看论坛这种是硬件问——已经换X86路由了，R2S只能吃灰了，用软路由就可以播号。
